README.rst, tox.ini
Messed up the tox config for coveralls reporting. This should fix it.
=> fixing coverage

tox.ini
Last one then I'll stop futzing around with this.
=> increasing test coverage: adding pyyaml

setup.cfg, src/dsdlgenj, src/pydsdlgen/__init__.py, src/pydsdlgen/generators.py, src/pydsdlgen/jinja/__init__.py, src/pydsdlgen/jinja/lang/c.py, src/pydsdlgen/lib.rst, test/fixtures/__init__.py, test/gentest_dsdl/test_dsdl.py, test/gentest_json/test_json.py, test/gentest_lang/dsdl/langtest/c/31745.TestType.0.1.uavcan, test/gentest_lang/dsdl/langtest/cpp/ns/31746.TestType.0.1.uavcan, test/gentest_lang/templates/StructureType.j2, test/gentest_lang/test_lang.py
Also adding namespace filters for c++, increasing coverage, and fixing a bug or two.
=> cleaning up library internals

setup.cfg
Pushing to upstream is evil. Sorry.
=> fixing mypy break

setup.cfg, setup.py, src/dev.rst, src/pydsdlgen/__init__.py, src/pydsdlgen/jinja/__init__.py, src/pydsdlgen/jinja/lang/c.py, src/pydsdlgen/version.py, src/templates.rst, test/fixtures/__init__.py, test/gentest_any/test_any.py, test/gentest_dsdl/templates/StructureType.j2, test/gentest_dsdl/templates/UnionType.j2, test/gentest_dsdl/test_dsdl.py, test/gentest_json/templates/BooleanType.j2, test/gentest_json/templates/StructureType.j2, test/gentest_json/templates/UnsignedIntegerType.j2, test/gentest_json/test_json.py, test/gentest_lang/templates/StructureType.j2, test/gentest_lang/test_lang.py, test/gentest_lookup/test_lookup.py, test/gentest_multiple/templates/StructureType.j2, test/gentest_multiple/test_multiple.py, tox.ini
1. Fixing places where I was mixing attributes and fields.
2. Fixing places I was using fields when I wanted attributes.
3. Cleaning up errors in the docs.
=> Fixes #19 and #24: fixing useage of attributes

.gitignore, CONTRIBUTING.rst, README.rst, setup.cfg, src/nnvg, src/nunavut/postprocessors.py, src/nunavut/version.py, test/fixtures/__init__.py, test/gentest_filters/test_filters.py, test/gentest_multiple/test_multiple.py, test/gentest_postprocessors/ext_program.py, test/gentest_postprocessors/templates/Any.j2, test/gentest_postprocessors/test_postprocessors.py
Fixing issue #37 and doing a bunch of other cleanup.
=> External Program support #37

setup.cfg, src/nunavut/version.py
https://github.com/UAVCAN/pydsdl/pull/33
=> Use PyDSDL v1.2

conftest.py, src/nunavut/version.py
=> removing unintended snark about Sybil

.vscode/settings.json, src/nunavut/cli.py, src/nunavut/version.py, test/gentest_nnvg/dsdl/fixedid/100.Timer.1.0.uavcan, test/gentest_nnvg/test_nnvg.py
Adds feature requested by #126
=> issue #126, adding allow unregulated arg to nnvg

conftest.py, src/nunavut/version.py
Realized my sybil changes were breaking generic pytest discovery.
=> fixing pytest discovery problems

.vscode/settings.json, conftest.py, src/nunavut/lang/c/templates/Header.j2, src/nunavut/lang/cpp/templates/Header.j2, src/nunavut/version.py, test/gentest_versions/dsdl/viruses/1.covid.1.10.uavcan, test/gentest_versions/dsdl/viruses/1.covid.1.9.uavcan, test/gentest_versions/test_versions.py
=> Fixing include guard generation for build-in templates

CONTRIBUTING.rst, verification/CMakeLists.txt
Added instructions for manually building native verification tests and added support for environment variables in the CMakeLists.txt
=> Improvements to the native build instructions for contributors

src/nunavut/lang/c/__init__.py, src/nunavut/lang/cpp/__init__.py, src/nunavut/version.py, test/gentest_any/dsdl/uavcan/time/510.GetSynchronizationMasterInfo.0.1.uavcan, test/gentest_any/dsdl/uavcan/time/SynchronizedAmbiguousTimestamp.1.0.uavcan, test/gentest_any/dsdl/uavcan/time/SynchronizedTimestamp.1.0.uavcan, test/gentest_filters/dsdl/new/hotness.1.0.uavcan, test/gentest_filters/dsdl/new/malloc.1.0.uavcan, test/gentest_filters/dsdl/uavcan/str/7168.bar.1.0.uavcan, test/gentest_filters/dsdl/uavcan/str/bar_svc.1.0.uavcan, test/gentest_filters/dsdl/uavcan/time/SynchronizedTimestamp.1.0.uavcan, test/gentest_filters/templates/full_reference_test/Any.j2, test/gentest_filters/templates/full_reference_test/ServiceType.j2, test/gentest_filters/test_filters.py, test/gentest_nnvg/dsdl/fixedid/100.Timer.1.0.uavcan, test/gentest_nnvg/dsdl/herringtec/TImer.2.1.uavcan, test/gentest_nnvg/dsdl/scotec/Timer.1.0.uavcan, test/gentest_nnvg/dsdl/uavcan/test/TestType.0.8.uavcan, test/gentest_postprocessors/dsdl/uavcan/test/TestType.0.2.uavcan, test/gentest_serialization/dsdl/basic/1.HelloSerialization.1.0.uavcan, test/gentest_serialization/dsdl/basic/Basic.1.0.uavcan, test/gentest_serialization/dsdl/complex/2.KitchenSink.1.0.uavcan, test/gentest_serialization/dsdl/complex/Nested.1.0.uavcan, test/gentest_serialization/dsdl/complex/NestedNested.1.0.uavcan, test/gentest_serialization/dsdl/complex/NestedUnion.1.0.uavcan, test/gentest_serialization/dsdl/complex/NestedUnionWComplexArray.1.0.uavcan, test/gentest_tests/dsdl/buncho/serializables.0.1.uavcan, verification/c/suite/test_compiles.cpp
We've changed both the requirement to have either @sealed or @extent and how we treat service types.
This fixes issue #152  and #153
=> Fixes for pydsdl changes

setup.cfg, src/nunavut/version.py
To prevent issues like https://forum.uavcan.org/t/unknown-directive-sealed-error-when-trying-to-generate-from-dsdl/955/14
=> Bump PyDSDL version number

setup.cfg, src/nunavut/version.py
Expectedly, this change did not break anything.
Fixes #154
=> Remove dangling dependency on setuptools (fix #154)

src/nunavut/version.py
My apologies in but in #189 I forgot to bump the version, this PR does.
=> Bump version

src/nunavut/jinja/__init__.py, src/nunavut/version.py, test/gentest_filters/dsdl/one/foo.1.0.uavcan, test/gentest_filters/templates/to_unique/Any.j2, test/gentest_filters/test_filters.py, test/gentest_serialization/dsdl/complex/2.KitchenSink.1.0.uavcan
Um, well. Colour me embarrassed but it appears that the unique filter does work with the template cache enabled. Paging @PetervdPerk-NXP.
Fixes #108
=> Somehow...this works

.vscode/settings.json, .vscode/spellright.dict, docs/templates.rst, src/nunavut/lang/cpp/__init__.py, src/nunavut/lang/cpp/templates/_composite_type.j2, src/nunavut/lang/cpp/templates/_fields.j2, src/nunavut/lang/cpp/templates/_fields_as_union.j2, src/nunavut/lang/properties.yaml, src/nunavut/version.py
Quckie to add your awesome new dsdl docs into the budding C++ types.
=> Adding dsdl doc to generated code

.github/verify.py, .github/workflows/test_and_release.yml, .vscode/c_cpp_properties.json, .vscode/cmake-kits.json, .vscode/settings.json, README.rst, src/nunavut/lang/cpp/__init__.py, verification/c/suite/test_override_variable_array_capacity.c
closes #228
Also fixes a sq code-smell.
=> Add C++17 build to CI

.github/workflows/test_and_release.yml, setup.cfg, src/nunavut/jinja/loaders.py, src/nunavut/version.py, tox.ini
Pytest 7 and Sybil 3 don't agree. Opened
https://github.com/simplistix/sybil/issues/37 and limited our pytest
dependency to be < 7.0
This fixes #237
=> Fixing linting error and pytest error

src/nunavut/version.py
This is the version bump I missed doing for #246
=> Bump version to v1.7.5 for #246

.github/verify.py, .github/verify_c_clang_native32.ini, .github/verify_c_clang_native64.ini, .github/verify_c_gcc_native32.ini, .github/verify_c_gcc_native64.ini, .github/verify_cpp_clang_native32.ini, .github/verify_cpp_clang_native64.ini, .github/verify_cpp_gcc_native32.ini, .github/verify_cpp_gcc_native64.ini, .github/workflows/test_and_release.yml, CONTRIBUTING.rst, src/nunavut/lang/cpp/support/serialization.j2, src/nunavut/version.py, verification/.devcontainer/native.Dockerfile
1. Adding explicit little-endian tests to CI
2. Fixing issues found by said tests.
3. Small documentation fixes and update to public_regulated_data_types
submodule.
=> Fixing #254 with tests

src/nunavut/lang/cpp/support/serialization.j2, src/nunavut/version.py
This fixes #254 for missing includes.
=> Fix missing includes

src/nunavut/_version.py, src/nunavut/lang/cpp/templates/_composite_type.j2
Fixes https://github.com/OpenCyphal/nunavut/issues/293
=> C++: Remove extra brace from the deprecated attribute

.github/workflows/release.yml, src/nunavut/_version.py, src/nunavut/jinja/__init__.py
`--template` argument should not apply to support files.
=> fix for #310

.github/workflows/release.yml, .github/workflows/test.yml, setup.cfg, src/nunavut/_version.py, tox.ini, verification/CMakeLists.txt
Fixes issue #331. Python 3.7 is EoL
=> Removing Python 3.7 support

.github/verify.py, NunavutConfig.cmake, docs/cmake/CMakeLists.txt
Fixes a couple of foibles. Works as documented with this change.
=> Finishing cmake integration

NunavutConfig.cmake, docs/cmake/CMakeLists.txt, docs/cmake/CMakePresets.json
Need to add verification test of this cmake. Sorry for the noise.
=> Fixing cmake output path
