.gitignore, Dockerfile, README.md
I changed 'pydsdlgen' to 'repo' so we can reuse this container for all of our python tox testing.
=> Making toxic container more generic

setup.cfg
This is needed to ensure that the latest patches are pulled in. They are needed for compatibility with https://github.com/UAVCAN/public_regulated_data_types/pull/73
=> Raise the minimum required version of PyDSDL

docs/api/modules.rst
This would appear to be my third commit here. All very helpful I'm certain.
=> Fix typo in modules.rst

setup.cfg, src/nunavut/cli.py, src/nunavut/jinja/__init__.py, src/nunavut/lang/py.py, src/nunavut/version.py, test/gentest_any/test_any.py, test/gentest_json/test_json.py, test/gentest_lang/test_lang.py, test/gentest_postprocessors/test_postprocessors.py, test/gentest_tests/test_tests.py
Fixes #108 by enabling [bytecode caching](https://jinja.palletsprojects.com/en/2.11.x/api/#bytecode-cache) in Jinja. PyUAVCAN tests pass. Ready to merge if CI is green.
The case described in #108 is down from 55 seconds to 7.7 seconds. Performance profile: [out-bytecode-cache-cumulative.tar.gz](https://github.com/UAVCAN/nunavut/files/4464928/out-bytecode-cache-cumulative.tar.gz)
=> Fix Python dependency imports, fix minor PyDSDL API usage issues

README.rst, conftest.py, tox.ini
Testing:
Test was manual since the README.rst is limited by github's ability to
parse it (i.e. Sybil sections would have been garbage).
1. Manually copied and pasted template text with change to a folder
`templates`
2. Using the specification example provided in section 3.8.3.4 invoked
`nnvg -l c my_dsdl_root_namespace/sirius_cyber_corp/ --templates
templates`
=> Fix README example per #118

conftest.py, src/nunavut/cli.py, src/nunavut/version.py, test/gentest_nnvg/test_nnvg.py
When using nnvg (i.e. this is not an intrinsic feature of the Nunavut
library) the target language can be inferred if only an output extension
is given. This was reported in issue #116.
=> Inferring target language from extension

conftest.py, src/nunavut/__init__.py, src/nunavut/cli.py, src/nunavut/generators.py, src/nunavut/jinja/__init__.py, src/nunavut/lang/__init__.py, src/nunavut/lang/_common.py, src/nunavut/lang/c/__init__.py, src/nunavut/lang/c/support/__init__.py, src/nunavut/lang/cpp/__init__.py, src/nunavut/lang/cpp/support/__init__.py, src/nunavut/lang/cpp/support/serialization.j2, src/nunavut/version.py, test/gentest_any/test_any.py, test/gentest_filters/test_filters.py, test/gentest_json/test_json.py, test/gentest_lang/test_lang.py, test/gentest_lookup/test_lookup.py, test/gentest_multiple/test_multiple.py, test/gentest_namespaces/test_namespaces.py, test/gentest_nnvg/test_nnvg.py, test/gentest_postprocessors/test_postprocessors.py, test/gentest_serialization/test_serialization.py, test/gentest_tests/test_tests.py
WIth this change the support headers can be `.j2` Jinja templates. When they are rendered there will be no `T` available (i.e. these are not generated per-type) but the target language environment will be available including language options like `option_target_endianness`.
=> Adding support header templates 

docs/static/css/custom.css, src/nunavut/version.py
I am not particularly opinionated about this but I was just working on moving the PyDSDL docs to ReadTheDocs and I thought that I should introduce the layout fix into Nunavut as well because this doesn't look right:
The effect of this change can be seen in the PyUAVCAN docs.
I wonder if I should propose this fix upstream...
=> Docs CSS: fix display on wide screens

docs/templates.rst, src/nunavut/jinja/__init__.py, src/nunavut/version.py
https://github.com/UAVCAN/nunavut/issues/33#issuecomment-485536105:
> First off, Jinja provides pretty fine-grained whitespace control so I don't think we'll authored templates should need any further processing.
Manual whitespace (blank line) management is getting really tedious. I prefer to not think about this if I can help it.
(╯°□°)╯︵ ┻━┻
=> Add filter for selective blank lines removal

src/nunavut/lang/_common.py, src/nunavut/version.py
The `__str__()` method of a `pathlib.Path` [is platform-dependent](https://docs.python.org/3.8/library/pathlib.html#operators).  We were using this when generating `#include` directives, but to produce host-independent C/C++ code we probably shouldn't (e.g. so that code generated on Windows can compile on a Linux system without Windows-style).
The current behaviour ultimately stems from the fact that the implementation presented at `pathlib.Path` depends on the interpreter host platform.  These are individually available as the `PosixPath` and `WindowsPath` classes.
An alternative to this PR would be to use `pathlib.PosixPath` (or `PurePosixPath`) around the code explicitly, rather than relying on platform-dependent behaviour.  However, it would probably be a much bigger diff than this …
=> Use POSIX-style paths in #includes

src/nunavut/cli.py, src/nunavut/version.py
One line fix: since we don't consume language_options unless we select a target language it's fine to just always pass it in.
=> fix for issue #142

src/nunavut/cli.py, src/nunavut/lang/__init__.py, src/nunavut/lang/properties.ini, src/nunavut/version.py, test/gentest_nnvg/test_nnvg.py, tox.ini
A second approach to denoting 'experimental' languages (i.e. anything that's not C or Python for v1.0).
Controversially, I've chosen for the CLI to default to supplying `include_experimental_languages` as `False` when creating a LanguageContext, although in `LanguageContext.__init__` itself the default is `True`.  This would mean that most of the test code (and any Pythonic users of nunavut rather than CLI users) will have experimental languages available by default -- let me know how you feel about this.  My main motivations for that choice are that the bulk of the test code, which uses C++ and JSON outputs, can be left intact this way, and that the original issue #172 seems concerned mainly with CLI users.
@thirtytwobits please correct me if wrong - is Python stable, or is it just C …
=> Differentiate between stable/experimental languages in API and CLI

src/nunavut/lang/__init__.py
Really small PR here. Noticed that there was a missing .format() on this warning, so I added it.
Not sure how strict the issue -> PR etiquette is on this project - this is just a one-line bugfix, but if the procedure is to open an issue then I can open one.
=> Fix missing .format in experimental language warning

.buildkite/verify.py, .buildkite/verify_c_amd64.sh, .buildkite/verify_c_x86.sh, CONTRIBUTING.rst, src/nunavut/cli.py, src/nunavut/lang/c/templates/definitions.j2, src/nunavut/lang/c/templates/serialization.j2, src/nunavut/lang/properties.ini, test/gentest_nnvg/templates/Any.j2, verification/CMakeLists.txt, verification/c/suite/test_override_variable_array_capacity.c, verification/cmake/modules/Findnnvg.cmake
Allow override ARRAY_CAPACITY in variable array to optimize publisher memory usage at compile time.
As a publisher you might already know the maximum size of variable length array. This commit allow to override the XXXX_ARRAY_CAPACITY_ define for variable length arrays.
A good example would be the reg_drone_service_battery_Status_0_2_cell_voltages_ARRAY_CAPACITY_ define. At default the maximum is 255, but for instance your BMS only supports atmost 6 cells.
By default the reg.drone.service.battery.Status_0.2 struct is 1056 bytes
```
hovergames@hovergames:~/uavcan/nunavut_redefine_test$ ./nunavut_redefine_test 
Size of reg_drone_service_battery_Status_0_2 1056
```
By allowing to overrule the cell_voltages array capacity we can decrease the struct size tremendously.
```
#include <stdio.h> …
```
=> Allow override ARRAY_CAPACITY in variable array 

setup.cfg, src/nunavut/jinja/__init__.py, src/nunavut/lang/c/templates/deserialization.j2, src/nunavut/lang/c/templates/serialization.j2, src/nunavut/version.py, tox.ini, verification/nunavut_test_types/test0/regulated/CombinatorialExplosion.0.1.uavcan
This fixes the combinatorial explosion problem described in https://github.com/UAVCAN/pydsdl/issues/23. Related changes in PyDSDL at https://github.com/UAVCAN/pydsdl/pull/66
Nunavut is still a bit slow (~47 seconds for the `uavcan` namespace) but its performance is now invariant to the complexity of the bit layouts of generated types and depends only on the number of generated types (I suspect the culprit is somewhere around the line buffering logic). For reference, generating these types used to take around 10 minutes, now it takes 6 seconds (x100 faster): https://github.com/pavel-kirienko/yukon/tree/master/yukon/dsdl_src/public_unregulated_data_types/org_uavcan_yukon
The tests are broken for reasons not related to this PR. @thirtytwobits You seem to have modified the Buildkite PR build …
=> Update C templates to use the new bit length set API

setup.py
Previously, JS and CSS assets in the HTML template directory would not be included in the built package, causing HTML documentation generation to fail. This PR fixes this issue by including JS and CSS assets via setup.py package_data.
=> Fix JS/CSS Asset Include into Nunavut

src/nunavut/lang/c/templates/definitions.j2, src/nunavut/lang/c/templates/deserialization.j2, src/nunavut/version.py, verification/c/suite/test_serialization.c
closes #221
Bump version number for release.
=> Fixing deserialization logic error in C

README.rst, docs/templates.rst, src/nunavut/lang/c/templates/base.j2, src/nunavut/lang/cpp/templates/base.j2, src/nunavut/version.py, test/gentest_json/templates/StructureType.j2
Fix windows paths that break building on windows, most notably because of static asserts. Backslashes were not properly escaped. In the abscence of a better fix, this replaces backslashes with double backslash in jinja templates, as backslashes should not be used on linux anyway.
=> Fixed windows paths

src/nunavut/version.py
This is a separate patch to update googletest.
=> Update googletest to a vesrion compatible with GCC11

src/nunavut/lang/c/__init__.py, src/nunavut/lang/cpp/__init__.py, src/nunavut/lang/cpp/support/serialization.j2, src/nunavut/lang/cpp/templates/_composite_type.j2, src/nunavut/lang/cpp/templates/_definitions.j2, src/nunavut/lang/cpp/templates/_fields_as_union.j2, src/nunavut/lang/cpp/templates/_fields_as_variant.j2, src/nunavut/lang/cpp/templates/deserialization.j2, src/nunavut/lang/cpp/templates/serialization.j2, src/nunavut/lang/properties.yaml, src/nunavut/version.py, verification/cpp/suite/test_bitarray.cpp, verification/cpp/suite/test_compiles.cpp, verification/cpp/suite/test_helpers.hpp, verification/cpp/suite/test_serialization.cpp
This PR is my attempt to create a working modern-looking (de)serialization layer for UAVCAN v1. This work is aimed at #91 progress.
Steps:
=> C++ language implementation (first steps)

src/nunavut/lang/_common.py, src/nunavut/version.py
Fixes #249 although this is not an adequate long-term solution, that one is tracked in https://github.com/UAVCAN/nunavut/issues/60
Tested this manually on a Windows 10 VM
=> Quick fix for 249 -- incorrect C/C++ include path separators on Windows

src/nunavut/lang/cpp/__init__.py, src/nunavut/lang/cpp/support/serialization.j2, src/nunavut/lang/cpp/templates/ServiceType.j2, src/nunavut/lang/cpp/templates/_composite_type.j2, test/gentest_filters/test_filters.py, verification/cpp/suite/test_bitarray.cpp, verification/cpp/suite/test_serialization.cpp
This patch includes some quality-of-life improvements:
1. All external methods in serialization support header-only library are now marked with `inline` to avoid linker errors if serialization code was included from several different translation units.
2. Refactor `bitspan` constructors to make user code easier and should fix #254.
```cpp
uavcan::node::Heartbeat_1_0 hb{};
std::array<uint8_t, uavcan::node::Heartbeat_1_0::SERIALIZATION_BUFFER_SIZE_BYTES> data;
// before change:
hb.serialize({{data}, 0});
// after change:
hb.serialize(data);
```
3. Change naming of service types from `uavcan::node::GetInfo_1_0::Request_1_0` to `uavcan::node::GetInfo::Request_1_0`
4. Add a special service type alongside `Request` and `Response` and some constexpr boolean traits to ease templating on services: …
=> Fix cpp implementations

setup.cfg, src/nunavut/version.py, tox.ini
https://github.com/OpenCyphal/pydsdl/releases/tag/1.16.0
=> Require PyDSDL v1.16 at least to ensure support for *.dsdl file extension

CONTRIBUTING.rst, src/nunavut/_version.py, src/nunavut/jinja/__init__.py, src/nunavut/jinja/environment.py, src/nunavut/jinja/extensions.py, src/nunavut/lang/__init__.py, src/nunavut/lang/_common.py, src/nunavut/lang/cpp/support/serialization.j2, src/nunavut/lang/cpp/support/variable_length_array.hpp, src/nunavut/lang/cpp/templates/_fields_as_union.j2, verification/cmake/modules/Findgtest.cmake, verification/cpp/suite/test_helpers.hpp, verification/cpp/suite/test_serialization.cpp, verification/cpp/suite/test_var_len_arr.cpp, verification/cpp/suite/test_var_len_arr_compiles.cpp
- Add bool specialization for VariableLengthArray; fix #260 
- Fix #281 
- Update Google Test to the latest version v1.13
- Fix incorrect handling of compilation flags in `Findgtest.cmake`
- Fix warnings revealed by the above fix
There is a fair amount of code duplication between the generic and specialized versions of `VariableLengthArray`. It is possible to eliminate some of it by extracting commonalities into a base class.
=> Add bool specialization for VariableLengthArray; fix AUTOSAR compliance issues; fix GTest integration

src/nunavut/_version.py, src/nunavut/lang/cpp/support/serialization.j2, src/nunavut/lang/cpp/support/variable_length_array.hpp, src/nunavut/lang/cpp/templates/ServiceType.j2, src/nunavut/lang/cpp/templates/_composite_type.j2, src/nunavut/lang/cpp/templates/_fields.j2, src/nunavut/lang/cpp/templates/_fields_as_variant.j2, src/nunavut/lang/cpp/templates/deserialization.j2, src/nunavut/lang/cpp/templates/serialization.j2, test/gentest_arrays/test_arrays.py, verification/cpp/suite/test_bitarray.cpp, verification/cpp/suite/test_helpers.hpp, verification/cpp/suite/test_serialization.cpp, verification/cpp/suite/test_var_len_arr.cpp
Fixes #286 
In C++, `serialize` and `deserialize` are now free-standing functions. The alternative would be to name them `_serialize_` and `_deserialize_`, but I imagine this to be bad form.
One unused error tag `SERIALIZATION_INVALID_ARGUMENT` has been removed. The others have been renamed into CamelCase for consistency, as ALL_CAPS is reserved for macros.
I also added `_traits_::TypeOf` for introspection; it is often helpful in user code as the alternative requires the use of `decltype`:
We may also introduce a wrapper like `nunavut::traits<T>` if direct usage of `_traits_` is considered hard to read.
=> C++: Avoid name collisions and add missing const begin()/end() methods to VLA

src/nunavut/_version.py, src/nunavut/lang/c/templates/definitions.j2, src/nunavut/lang/c/templates/deserialization.j2, src/nunavut/lang/c/templates/serialization.j2, src/nunavut/lang/cpp/support/variable_length_array.hpp
- Closes https://github.com/OpenCyphal/nunavut/issues/178
- Also, fix benign warnings about uninitialized reads in C++ `VariableLengthArray<bool>`
=> Fix formatting inconsistencies in the C code generator (not C++)

src/nunavut/_version.py, src/nunavut/lang/cpp/templates/_composite_type.j2
Please review the syntax, I'm no Jinja expert. See #299 for explanation.
=> cpp: relocate the deprecated attribute to fix clang compilation (#299)

src/nunavut/lang/cpp/templates/_composite_type.j2, verification/cpp/suite/test_constant.cpp
- Addressed issue #353 
- Uncommented array capacity related unit test asserts.
=> Introduced `<Type>::_traits_::ArrayCapacity` struct.

src/nunavut/lang/c/support/serialization.j2
Small fix for clang-tidy false positive about using garbage data during serialization, like following:
```
/home/runner/work/demos/demos/libudpard_demo/build/transpiled/nunavut/support/serialization.h:154:36: error: The left operand of '&' is a garbage value [clang-analyzer-core.UndefinedBinaryOperatorResult,-warnings-as-errors]
*last_dst = (*last_dst & (uint8_t)~mask) | (*last_src & mask);
^
```
=> Fix for "garbage" bits

src/nunavut/lang/cpp/support/serialization.j2, src/nunavut/lang/cpp/templates/deserialization.j2, verification/cpp/suite/test_bitarray.cpp, verification/cpp/suite/test_serialization.cpp
=> Fix for issue 370 : C++ generator deserialization
